### ISSUE TITLE
Enforce spacing after !

### ISSUE THREAD

**Issue by Gregliest** [TakeScoop/eslint-config-scoop#17]
Right now, the linter doesn't enforce (! <boolean>) vs. (!<boolean>).  Our style prefers the latter.

**Comment by Befall** [comment]
@Gregliest @hulbert Looking into it, I'm not seeing any rules currently part of ESLint that accommodate spacing around exclamation marks. The only option I can find is creating a custom rule, which I don't think we've done before. The process doesn't look too difficult to do, and could definitely provide a structure for any further custom rules we'd want to make in the future. Thoughts on that?

**Comment by Befall** [comment]
Nevermind, @eladidan found the rule I was looking for here: http://eslint.org/docs/rules/space-unary-ops
