### ISSUE TITLE
Version of eslint doesn't allow specifying ecmaVersion 10

### ISSUE THREAD

**Issue by GuyHadas** [TakeScoop/eslint-config-scoop#23]
The version of `eslint` that we're on does not yet support ecmaVersion 10 so apps on node 10 must specify `ecmaVersion: 8`.

**Comment by hulbert** [comment]
[This says](https://eslint.org/docs/user-guide/configuring#specifying-parser-options) `10` corresponds to `2019`. Is 2019 finalized?

**Comment by andrewtamura** [comment]
The hosted documentation is for the latest version of eslint (v5.x.x). Here are the docs for v4.9.0 https://github.com/eslint/eslint/blob/v4.9.0/docs/user-guide/configuring.md that show that `ecmaVersion: 10` is not supported in v4.9.0. 

FWIW, I can use eslint-config-scoop@4.0.0 with eslint@5.x.x without problems.

**Comment by hulbert** [comment]
Agreed, I'm more asking if we should even be using ES2019 yet if it's not standardized?

**Comment by hulbert** [comment]
And/or are they implemented in the versions of node we're using :D

**Comment by andrewtamura** [comment]
There are plenty of [stage0/1/2/3 proposals](https://github.com/tc39/proposals#active-proposals) that may make it into ecmaScript 10 eventually, but the finalized proposals (like [async iteration](https://github.com/tc39/proposal-async-iteration) and [object rest/spread operator](https://github.com/tc39/proposal-object-rest-spread)) should not be dropped from ecmaScript 10. I believe it is safe to use `ecmaVersion: 10` as eslint does not roll out new syntax rules [until proposals hit stage 4](https://github.com/eslint/eslint/issues/9885).

**Comment by hulbert** [comment]
@andrewtamura thanks for the context, makes sense. Looks like only four things got into ES2019 the main one being optional binding for catch blocks.

Setting to `ecmaVersion=10` should work as of the `5.0.0` release of this module since it uses `eslint@5`.
