### ISSUE TITLE
Should disallow multiline arrow function bodies without braces

### ISSUE THREAD

**Issue by hulbert** [TakeScoop/eslint-config-scoop#29]
There was some code like this:

```js
.then(function(x) {
    return Promise.map([6, 3], daysSince => 
        doSomething({
            x: 'x',
            daysAgo: daysSince
        })
    )
})
```

The lone `)` looks really out of place compared to rest of our code and readability here is harmed. This actually is an implicit return but looks like someone forgot to return or forgot to close a bracket.

**Comment by andrewtamura** [comment]
https://eslint.org/docs/rules/arrow-body-style will help here. The `as-needed` option looks appropriate 
```
/*eslint arrow-body-style: ["error", "as-needed"]*/
/*eslint-env es6*/

let foo = () => 0;
let foo = (retv, name) => {
    retv[name] = true;
    return retv;
};
let foo = () => ({
    bar: {
        foo: 1,
        bar: 2,
    }
});
let foo = () => { bar(); };
let foo = () => {};
let foo = () => { /* do nothing */ };
let foo = () => {
    // do nothing.
};
let foo = () => ({ bar: 0 });
```

**Comment by OJFord** [comment]
Note this doesn't prevent
```js
.then(function(x) {
    return Promise.map([6, 3], (daysSince) => doSomething({
      x: 'x',
      daysAgo: daysSince,
    }))
})
```

which is what I stumbled across this issue looking for a fix for.

Specifically because it gets weird in chaining:
```js
  const done = () => doSomething({
    x: 'x',
    daysAgo: daysSince,
  })
    .then(doOther)
```

where I'd prefer braces, parens, or perhaps ideally (but probably controversially) just extra indentation:
```js
  const done = () => doSomething({
      x: 'x',
      daysAgo: daysSince,
    })
    .then(doOther)
```

- _something_ to get the closing paren to align with the next chained call.
