### ISSUE TITLE
Multiline function invocation should place last parenthesis on a new line

### ISSUE THREAD

**Issue by hulbert** [TakeScoop/eslint-config-scoop#31]
From @andrewtamura 

```js
// wrong:
doSomething(
    doSomethingA,
    doSomethingB)

// correct:
doSomething(
    doSomethingA,
    doSomethingB
)
```

Andrew suggested we [can fix via the correct config of `function-paren-newline`](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGZ1bmN0aW9uLXBhcmVuLW5ld2xpbmU6IFtcImVycm9yXCIsIFwibXVsdGlsaW5lXCJdICovXG5cbi8vIHRoZXNlIGFyZSBnb29kIVxuZnVuY3Rpb24gZm9vKGJhciwgYmF6KSB7fVxuXG52YXIgZm9vID0gZnVuY3Rpb24oXG4gIGJhcixcbiAgYmF6XG4pIHt9O1xuXG52YXIgZm9vID0gKGJhciwgYmF6KSA9PiB7fTtcblxuZm9vKGJhciwgYmF6LCBxdXgpO1xuXG5mb28oXG4gIGJhcixcbiAgYmF6LFxuICBxdXhcbik7XG5cbmZvbyhmdW5jdGlvbigpIHtcbiAgcmV0dXJuIGJhejtcbn0pO1xuXG4vLyBUaGVzZSBhcmUgYmFkXG5mdW5jdGlvbiBmb28oYmFyLFxuICBiYXpcbikge31cblxudmFyIGZvbyA9IGZ1bmN0aW9uKFxuICBiYXIsIGJhelxuKSB7fTtcblxudmFyIGZvbyA9IChcbiAgYmFyLFxuICBiYXopID0+IHt9O1xuXG5mb28oYmFyLFxuICBiYXopO1xuXG5mb28oXG4gIGZ1bmN0aW9uKCkge1xuICAgIHJldHVybiBiYXo7XG4gIH1cbik7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19).

I **am** a bit worried that could cause regressions from our standard styles so we should include a more complete example file to test for that.

**Comment by andrewtamura** [comment]
@hulbert question around the concern of regressions. What are the exceptions to the proposed ESLint rule that may existing in the "standard styles"? Your linked ESLint playground (inserted below for clarity) looks consistent with the POV discussed in https://github.com/TakeScoop/handbook/issues/74. 
Any deviations from the proposed rule are incorrect and should be changed to conform to the rule right?
```
/* eslint function-paren-newline: ["error", "multiline"] */

// these are good!
function foo(bar, baz) {}

var foo = function(
  bar,
  baz
) {};

var foo = (bar, baz) => {};

foo(bar, baz, qux);

foo(
  bar,
  baz,
  qux
);

foo(function() {
  return baz;
});

// These are bad
function foo(bar,
  baz
) {}

var foo = function(
  bar, baz
) {};

var foo = (
  bar,
  baz) => {};

foo(bar,
  baz);

foo(
  function() {
    return baz;
  }
);
```

**Comment by hulbert** [comment]
@andrewtamura I misunderstood, I thought the new rule was called `multiline` but it's actually `function-paren-newline` so presumably that's a narrower scope. 

I still think having an anonymized complex example of "good code" from one of our larger codebases will be helpful in avoiding regressions.

**Comment by hulbert** [comment]
(But to be clear we could probably move ahead on this without that)
