### ISSUE TITLE
enforce commonJS import style

### ISSUE THREAD

**Issue by andrewtamura** [TakeScoop/eslint-config-scoop#34]
Our commonJS import style is not enforceable by the built-in eslint rules. We can write our own ESLint plugin to enforce our commonJS import style.

Here is the current style that we would like to enforce:
1) imports should be organized into three groupings: First: node core modules, second: any module that would get installed in node_modules, finally: project modules (local imports). Related discussion: https://github.com/TakeScoop/handbook/issues/82
2) Within each grouping, the assigned variables should be sorted by lexicographical order (e.g `bar` before `foo`)
3) the first grouping should have padding if the directive above is `use strict`

**Comment by ariwbolton** [comment]
I have some edge cases/potential improvements:

1. Should we have a "Bookshelf model group", too? I'm not totally sure how we'd enforce this, but the idea is that _most of the time_ we want to have all "model require" statements (exceptions include needing to import models within route handler functions, instead of at the module level).
2. Sometimes, imports for tests look like this:

```javascript
const Code = require('code')
const Lab = require('lab')
const moment = require('moment-timezone')
const lab = exports.lab = Lab.script() // <-

const describe = lab.describe // <-
const it = lab.it // <-
const expect = Code.expect // <-

const createAccount = require('../../../../testUtils/createAccount')
const dbUtil = require('../../../../testUtils/db')
...
```

It seems clear that having, standard, "import like" statements is a common (and encouraged) pattern. What should our policy be on this issue? (Asking because by the rules stated above, we'd simply move the four lines I've annotated above down below the "local imports", but this seems to not be preferable)

**Comment by andrewtamura** [comment]
I think the style for "import-like" variable declarations should be handled separately from the commonJS import style. From your code snippet, I believe the correct commonJS style would be as follows (inline comments are for clarity, not required by the plugin 😄):
```js
// imports from node_modules
const Code = require('code')
const Lab = require('lab')
const moment = require('moment-timezone')

// local imports
const createAccount = require('../../../../testUtils/createAccount')
const dbUtil = require('../../../../testUtils/db')

// the following lines are not commonJS imports.
const lab = exports.lab = Lab.script() // <-
const describe = lab.describe // <-
const it = lab.it // <-
const expect = Code.expect // <-
...
```

CommonJS imports use the special `require` function. Variable definitions without `require` are not commonJS imports. While the grouping and sorting of commonJS imports may also apply to variable definitions, I think that we should implement the commonJS import style first and implement the grouping of variables separately.  

@ariwbolton Can you open a discussion in https://github.com/TakeScoop/handbook/issues to make sure that the org is aligned on how we group import-like variables? It would be nice to enforce the grouping of variable declarations (bookshelf models, testing functions, etc), but first we should clarify that this POV is something we want to enforce in the linter.

**Comment by andrewtamura** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#newlines-between-ignorealwaysalways-and-inside-groupsnever

Ari found this, just posting so it doesn't get forgotten about. It looks like this eslint plugin will give us the groupings that we want. We should investigate if this plugin work with our current `rootRequire` pattern. Based on the implementation of this plugin, it appears to look for the [commonJS function named "require"](https://github.com/benmosher/eslint-plugin-import/blob/3b04d5fab6c095e7f0f99488665d90e285872271/src/core/staticRequire.js#L6) in order to identify if the expression is a commonJS import and may _not_ be compatible with `rootRequire`.

**Comment by hulbert** [comment]
@andrewtamura this plugin looks solid (if a bit big in terms of has lots of rules. Let's separate out the other conversations (test files, `rootRequire`) and go ahead and implement?

**Comment by andrewtamura** [comment]
@ariwbolton It looks like we can use the following rules to implement the [commonJS groupings style](https://github.com/takescoop/api/#nodejs-module-patterns):
- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#groups-array
- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#newlines-between-ignorealwaysalways-and-inside-groupsnever

Can you take a stab at a PR?
