### ISSUE TITLE
enforce spacing for `async` keyword

### ISSUE THREAD

**Issue by andrewtamura** [TakeScoop/eslint-config-scoop#35]
# Desired
```js
// One space after the `async` keyword
async () => stuff
async function() { ... }
```

# Not Desired
```js
// No spaces after the `async` keyword
async() => stuff
// More than one space after `async` keyword
async     () { ... }
```

**Comment by andrewtamura** [comment]
More than one space between `async` and the fat-arrow function may already be covered by existing rules.

**Comment by eladidan** [comment]
looks like this would be possible with: https://eslint.org/docs/rules/space-before-function-paren and `asyncArrow` parameter
