### ISSUE TITLE
Array spacing not enforced

### ISSUE THREAD

**Issue by randyxli** [TakeScoop/eslint-config-scoop#40]
See the following failing test: https://circleci.com/gh/TakeScoop/eslint-config-scoop/69

We should enforce the following style:

```javascript
['one', 'two']
```

over this style:

```javascript
[ 'one', 'two' ]
```

**Comment by hulbert** [comment]
https://eslint.org/docs/rules/array-bracket-spacing with default error settings enforces. Tested on internal codebase, seems reasonable to enable with semver minor.
