### ISSUE TITLE
Disallow use of the comma operator

### ISSUE THREAD

**Issue by samliebow** [TakeScoop/eslint-config-scoop#41]
I've never seen anybody deliberately use the [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator), but I've run into a couple cases of people accidentally using it where they meant to use a comma for something normal and being surprised that it wasn't a syntax error.

ESLint has the `no-sequences` [rule](https://eslint.org/docs/rules/no-sequences) that disallows the comma operator outside for-loops and expressions wrapped inside parentheses, but I think we should actually just bar it altogether:
```
{
    "rules": {
        "no-restricted-syntax": ["error", "SequenceExpression"]
    }
}
```

**Comment by samliebow** [comment]
I just tried to lint the API, and we have three usages, all clearly mistakes: [here](https://github.com/TakeScoop/api/blob/c254191c1a275f8556ad82d75fe32ea23445d4a3/app/lib/ProspectiveTrip.js#L45), [here](https://github.com/TakeScoop/api/blob/c254191c1a275f8556ad82d75fe32ea23445d4a3/app/lib/SecondSeatingProspect.js#L28), and [here](https://github.com/TakeScoop/api/blob/c254191c1a275f8556ad82d75fe32ea23445d4a3/test/unit/app/endpoints/private/trips/timeSlotGroups.js#L375-L376).

**Comment by hulbert** [comment]
Good find. Would appreciate a PR for `no-sequences` rule. I think this can be a semver minor release for us.
