### ISSUE TITLE
Enforce newline before returns

### ISSUE THREAD

**Issue by BuvSethia** [TakeScoop/eslint-config-scoop#43]
Add `[{ blankLine: "always", prev: "*", next: "return" }]` to the `padding-line-between-statements` config to enforce newlines before returns when the return statement is not the only line of code in the block. Examples of enforcement can be found here, the first example specifically:
https://eslint.org/docs/rules/padding-line-between-statements#examples

**Comment by samliebow** [comment]
Just gave this a spin on the API:
```
✖ 592 problems (592 errors, 0 warnings)
  592 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by BuvSethia** [comment]
Thanks for checking! Would be curious if `eslint --fix` will take care of the conflicts to make the upgrade painless if we decide to enforce. Maybe worth checking.

**Comment by andrewtamura** [comment]
New line padding isn’t particularly impactful for me, however I have heard that many people prefer the padding. I think this rule will improve the consistency and help focus code review time to more impactful aspects of the code. I’m all for this change!

**Comment by GuyHadas** [comment]
@BuvSethia were you planning on opening up a PR for this? Would be great to have this in as soon as possible since it continues to appear in Pull Requests.

**Comment by BuvSethia** [comment]
Yeah I can. Wasn't sure if we had decided for sure and then forgot to follow up, my bad
